//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboZZle.WebService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LevelInfo", Namespace="http://schemas.datacontract.org/2004/07/RoboCoder.GameState")]
    public partial class LevelInfo : object
    {
        
        private string AboutField;
        
        private int AllowedCommandsField;
        
        private string[] ColorsField;
        
        private int DifficultyVoteCountField;
        
        private int DifficultyVoteSumField;
        
        private int DislikedField;
        
        private bool FeaturedField;
        
        private int IdField;
        
        private string[] ItemsField;
        
        private int LikedField;
        
        private int RobotColField;
        
        private int RobotDirField;
        
        private int RobotRowField;
        
        private int SolutionsField;
        
        private int[] SubLengthsField;
        
        private string SubmittedByField;
        
        private System.DateTime SubmittedDateField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string About
        {
            get
            {
                return this.AboutField;
            }
            set
            {
                this.AboutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AllowedCommands
        {
            get
            {
                return this.AllowedCommandsField;
            }
            set
            {
                this.AllowedCommandsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Colors
        {
            get
            {
                return this.ColorsField;
            }
            set
            {
                this.ColorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DifficultyVoteCount
        {
            get
            {
                return this.DifficultyVoteCountField;
            }
            set
            {
                this.DifficultyVoteCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DifficultyVoteSum
        {
            get
            {
                return this.DifficultyVoteSumField;
            }
            set
            {
                this.DifficultyVoteSumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Disliked
        {
            get
            {
                return this.DislikedField;
            }
            set
            {
                this.DislikedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Featured
        {
            get
            {
                return this.FeaturedField;
            }
            set
            {
                this.FeaturedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Liked
        {
            get
            {
                return this.LikedField;
            }
            set
            {
                this.LikedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RobotCol
        {
            get
            {
                return this.RobotColField;
            }
            set
            {
                this.RobotColField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RobotDir
        {
            get
            {
                return this.RobotDirField;
            }
            set
            {
                this.RobotDirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RobotRow
        {
            get
            {
                return this.RobotRowField;
            }
            set
            {
                this.RobotRowField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Solutions
        {
            get
            {
                return this.SolutionsField;
            }
            set
            {
                this.SolutionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] SubLengths
        {
            get
            {
                return this.SubLengthsField;
            }
            set
            {
                this.SubLengthsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmittedBy
        {
            get
            {
                return this.SubmittedByField;
            }
            set
            {
                this.SubmittedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SubmittedDate
        {
            get
            {
                return this.SubmittedDateField;
            }
            set
            {
                this.SubmittedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LevelInfo2", Namespace="http://schemas.datacontract.org/2004/07/RoboCoder.GameState")]
    public partial class LevelInfo2 : object
    {
        
        private string AboutField;
        
        private int AllowedCommandsField;
        
        private string[] ColorsField;
        
        private int CommentCountField;
        
        private int DifficultyVoteCountField;
        
        private int DifficultyVoteSumField;
        
        private int DislikedField;
        
        private bool FeaturedField;
        
        private int IdField;
        
        private string[] ItemsField;
        
        private int LikedField;
        
        private int RobotColField;
        
        private int RobotDirField;
        
        private int RobotRowField;
        
        private int SolutionsField;
        
        private int[] SubLengthsField;
        
        private string SubmittedByField;
        
        private System.DateTime SubmittedDateField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string About
        {
            get
            {
                return this.AboutField;
            }
            set
            {
                this.AboutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AllowedCommands
        {
            get
            {
                return this.AllowedCommandsField;
            }
            set
            {
                this.AllowedCommandsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Colors
        {
            get
            {
                return this.ColorsField;
            }
            set
            {
                this.ColorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CommentCount
        {
            get
            {
                return this.CommentCountField;
            }
            set
            {
                this.CommentCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DifficultyVoteCount
        {
            get
            {
                return this.DifficultyVoteCountField;
            }
            set
            {
                this.DifficultyVoteCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DifficultyVoteSum
        {
            get
            {
                return this.DifficultyVoteSumField;
            }
            set
            {
                this.DifficultyVoteSumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Disliked
        {
            get
            {
                return this.DislikedField;
            }
            set
            {
                this.DislikedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Featured
        {
            get
            {
                return this.FeaturedField;
            }
            set
            {
                this.FeaturedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Liked
        {
            get
            {
                return this.LikedField;
            }
            set
            {
                this.LikedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RobotCol
        {
            get
            {
                return this.RobotColField;
            }
            set
            {
                this.RobotColField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RobotDir
        {
            get
            {
                return this.RobotDirField;
            }
            set
            {
                this.RobotDirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RobotRow
        {
            get
            {
                return this.RobotRowField;
            }
            set
            {
                this.RobotRowField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Solutions
        {
            get
            {
                return this.SolutionsField;
            }
            set
            {
                this.SolutionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] SubLengths
        {
            get
            {
                return this.SubLengthsField;
            }
            set
            {
                this.SubLengthsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmittedBy
        {
            get
            {
                return this.SubmittedByField;
            }
            set
            {
                this.SubmittedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SubmittedDate
        {
            get
            {
                return this.SubmittedDateField;
            }
            set
            {
                this.SubmittedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LevelVoteInfo", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class LevelVoteInfo : object
    {
        
        private int LevelIdField;
        
        private string UserNameField;
        
        private int VoteField;
        
        private int VoteKindField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LevelId
        {
            get
            {
                return this.LevelIdField;
            }
            set
            {
                this.LevelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vote
        {
            get
            {
                return this.VoteField;
            }
            set
            {
                this.VoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VoteKind
        {
            get
            {
                return this.VoteKindField;
            }
            set
            {
                this.VoteKindField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommentInfo", Namespace="http://schemas.datacontract.org/2004/07/RoboCoder.GameState")]
    public partial class CommentInfo : object
    {
        
        private bool AfterSolvingField;
        
        private string AuthorField;
        
        private string CommentField;
        
        private System.DateTime UtcTimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AfterSolving
        {
            get
            {
                return this.AfterSolvingField;
            }
            set
            {
                this.AfterSolvingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author
        {
            get
            {
                return this.AuthorField;
            }
            set
            {
                this.AuthorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UtcTimestamp
        {
            get
            {
                return this.UtcTimestampField;
            }
            set
            {
                this.UtcTimestampField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoboZZle.WebService.IRobozzleService")]
    public interface IRobozzleService
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/GetLevels", ReplyAction="http://tempuri.org/IRobozzleService/GetLevelsResponse")]
        System.Threading.Tasks.Task<RoboZZle.WebService.GetLevelsResponse> GetLevelsAsync(RoboZZle.WebService.GetLevelsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/GetLevels2", ReplyAction="http://tempuri.org/IRobozzleService/GetLevels2Response")]
        System.Threading.Tasks.Task<RoboZZle.WebService.GetLevels2Response> GetLevels2Async(RoboZZle.WebService.GetLevels2Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/GetLevels3", ReplyAction="http://tempuri.org/IRobozzleService/GetLevels3Response")]
        System.Threading.Tasks.Task<RoboZZle.WebService.GetLevels3Response> GetLevels3Async(RoboZZle.WebService.GetLevels3Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/GetLevelsPaged", ReplyAction="http://tempuri.org/IRobozzleService/GetLevelsPagedResponse")]
        System.Threading.Tasks.Task<RoboZZle.WebService.GetLevelsPagedResponse> GetLevelsPagedAsync(RoboZZle.WebService.GetLevelsPagedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/GetLevel", ReplyAction="http://tempuri.org/IRobozzleService/GetLevelResponse")]
        System.Threading.Tasks.Task<RoboZZle.WebService.LevelInfo2> GetLevelAsync(int levelId);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/SubmitLevel", ReplyAction="http://tempuri.org/IRobozzleService/SubmitLevelResponse")]
        System.Threading.Tasks.Task<RoboZZle.WebService.SubmitLevelResponse> SubmitLevelAsync(RoboZZle.WebService.SubmitLevelRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/SubmitLevel2", ReplyAction="http://tempuri.org/IRobozzleService/SubmitLevel2Response")]
        System.Threading.Tasks.Task<RoboZZle.WebService.SubmitLevel2Response> SubmitLevel2Async(RoboZZle.WebService.SubmitLevel2Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/LogIn", ReplyAction="http://tempuri.org/IRobozzleService/LogInResponse")]
        System.Threading.Tasks.Task<RoboZZle.WebService.LogInResponse> LogInAsync(RoboZZle.WebService.LogInRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/LogIn2", ReplyAction="http://tempuri.org/IRobozzleService/LogIn2Response")]
        System.Threading.Tasks.Task<RoboZZle.WebService.LogIn2Response> LogIn2Async(RoboZZle.WebService.LogIn2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/SubmitSolution", ReplyAction="http://tempuri.org/IRobozzleService/SubmitSolutionResponse")]
        System.Threading.Tasks.Task<string> SubmitSolutionAsync(int levelId, string userName, string password, string solution);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/RegisterUser", ReplyAction="http://tempuri.org/IRobozzleService/RegisterUserResponse")]
        System.Threading.Tasks.Task<string> RegisterUserAsync(string userName, string password, string email, int[] solvedLevels);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/RegisterUser2", ReplyAction="http://tempuri.org/IRobozzleService/RegisterUser2Response")]
        System.Threading.Tasks.Task<string> RegisterUser2Async(string userName, string password, string email, System.Collections.Generic.Dictionary<int, string> solvedLevels);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/GetTopSolvers", ReplyAction="http://tempuri.org/IRobozzleService/GetTopSolversResponse")]
        System.Threading.Tasks.Task<RoboZZle.WebService.GetTopSolversResponse> GetTopSolversAsync(RoboZZle.WebService.GetTopSolversRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/Internal", ReplyAction="http://tempuri.org/IRobozzleService/InternalResponse")]
        System.Threading.Tasks.Task InternalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/SubmitLevelVote", ReplyAction="http://tempuri.org/IRobozzleService/SubmitLevelVoteResponse")]
        System.Threading.Tasks.Task SubmitLevelVoteAsync(string userName, string password, int levelId, int vote0, int vote1);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/GetLevelVotes", ReplyAction="http://tempuri.org/IRobozzleService/GetLevelVotesResponse")]
        System.Threading.Tasks.Task<RoboZZle.WebService.GetLevelVotesResponse> GetLevelVotesAsync(RoboZZle.WebService.GetLevelVotesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/SubmitComment", ReplyAction="http://tempuri.org/IRobozzleService/SubmitCommentResponse")]
        System.Threading.Tasks.Task SubmitCommentAsync(string userName, string password, int puzzleId, string comment, string ipAddress);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/GetTopSolvers2", ReplyAction="http://tempuri.org/IRobozzleService/GetTopSolvers2Response")]
        System.Threading.Tasks.Task<RoboZZle.WebService.GetTopSolvers2Response> GetTopSolvers2Async(RoboZZle.WebService.GetTopSolvers2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/GetLevelSolutionLengths", ReplyAction="http://tempuri.org/IRobozzleService/GetLevelSolutionLengthsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, int>> GetLevelSolutionLengthsAsync(int levelId);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/GetLevelComments", ReplyAction="http://tempuri.org/IRobozzleService/GetLevelCommentsResponse")]
        System.Threading.Tasks.Task<RoboZZle.WebService.GetLevelCommentsResponse> GetLevelCommentsAsync(RoboZZle.WebService.GetLevelCommentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobozzleService/GetSolutions", ReplyAction="http://tempuri.org/IRobozzleService/GetSolutionsResponse")]
        System.Threading.Tasks.Task<string[]> GetSolutionsAsync(string userName, string password, int puzzleId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLevels", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLevelsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int levelId;
        
        public GetLevelsRequest()
        {
        }
        
        public GetLevelsRequest(int levelId)
        {
            this.levelId = levelId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLevelsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLevelsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RoboZZle.WebService.LevelInfo[] GetLevelsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Collections.Generic.Dictionary<int, int> commentCounts;
        
        public GetLevelsResponse()
        {
        }
        
        public GetLevelsResponse(RoboZZle.WebService.LevelInfo[] GetLevelsResult, System.Collections.Generic.Dictionary<int, int> commentCounts)
        {
            this.GetLevelsResult = GetLevelsResult;
            this.commentCounts = commentCounts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLevels2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLevels2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int levelId;
        
        public GetLevels2Request()
        {
        }
        
        public GetLevels2Request(int levelId)
        {
            this.levelId = levelId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLevels2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLevels2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RoboZZle.WebService.LevelInfo[] GetLevels2Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Collections.Generic.Dictionary<int, int> commentCounts;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int[] campaign;
        
        public GetLevels2Response()
        {
        }
        
        public GetLevels2Response(RoboZZle.WebService.LevelInfo[] GetLevels2Result, System.Collections.Generic.Dictionary<int, int> commentCounts, int[] campaign)
        {
            this.GetLevels2Result = GetLevels2Result;
            this.commentCounts = commentCounts;
            this.campaign = campaign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLevels3", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLevels3Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int levelId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int fromLevelId;
        
        public GetLevels3Request()
        {
        }
        
        public GetLevels3Request(int levelId, int fromLevelId)
        {
            this.levelId = levelId;
            this.fromLevelId = fromLevelId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLevels3Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLevels3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RoboZZle.WebService.LevelInfo[] GetLevels3Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Collections.Generic.Dictionary<int, int> commentCounts;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int[] campaign;
        
        public GetLevels3Response()
        {
        }
        
        public GetLevels3Response(RoboZZle.WebService.LevelInfo[] GetLevels3Result, System.Collections.Generic.Dictionary<int, int> commentCounts, int[] campaign)
        {
            this.GetLevels3Result = GetLevels3Result;
            this.commentCounts = commentCounts;
            this.campaign = campaign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLevelsPaged", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLevelsPagedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int blockIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int blockSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int sortKind;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string unsolvedByUser;
        
        public GetLevelsPagedRequest()
        {
        }
        
        public GetLevelsPagedRequest(int blockIndex, int blockSize, int sortKind, string unsolvedByUser)
        {
            this.blockIndex = blockIndex;
            this.blockSize = blockSize;
            this.sortKind = sortKind;
            this.unsolvedByUser = unsolvedByUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLevelsPagedResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLevelsPagedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RoboZZle.WebService.LevelInfo2[] GetLevelsPagedResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int totalCount;
        
        public GetLevelsPagedResponse()
        {
        }
        
        public GetLevelsPagedResponse(RoboZZle.WebService.LevelInfo2[] GetLevelsPagedResult, int totalCount)
        {
            this.GetLevelsPagedResult = GetLevelsPagedResult;
            this.totalCount = totalCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitLevel", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SubmitLevelRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RoboZZle.WebService.LevelInfo level;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string solution;
        
        public SubmitLevelRequest()
        {
        }
        
        public SubmitLevelRequest(RoboZZle.WebService.LevelInfo level, string userName, string pwd, string solution)
        {
            this.level = level;
            this.userName = userName;
            this.pwd = pwd;
            this.solution = solution;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitLevelResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SubmitLevelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SubmitLevelResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int levelId;
        
        public SubmitLevelResponse()
        {
        }
        
        public SubmitLevelResponse(string SubmitLevelResult, int levelId)
        {
            this.SubmitLevelResult = SubmitLevelResult;
            this.levelId = levelId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitLevel2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SubmitLevel2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RoboZZle.WebService.LevelInfo2 level2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string solution;
        
        public SubmitLevel2Request()
        {
        }
        
        public SubmitLevel2Request(RoboZZle.WebService.LevelInfo2 level2, string userName, string pwd, string solution)
        {
            this.level2 = level2;
            this.userName = userName;
            this.pwd = pwd;
            this.solution = solution;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitLevel2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SubmitLevel2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SubmitLevel2Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int levelId;
        
        public SubmitLevel2Response()
        {
        }
        
        public SubmitLevel2Response(string SubmitLevel2Result, int levelId)
        {
            this.SubmitLevel2Result = SubmitLevel2Result;
            this.levelId = levelId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogIn", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LogInRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        public LogInRequest()
        {
        }
        
        public LogInRequest(string userName, string password)
        {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogInResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LogInResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool LogInResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int[] solvedLevels;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public RoboZZle.WebService.LevelVoteInfo[] votes;
        
        public LogInResponse()
        {
        }
        
        public LogInResponse(bool LogInResult, int[] solvedLevels, RoboZZle.WebService.LevelVoteInfo[] votes)
        {
            this.LogInResult = LogInResult;
            this.solvedLevels = solvedLevels;
            this.votes = votes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogIn2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LogIn2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        public LogIn2Request()
        {
        }
        
        public LogIn2Request(string userName, string password)
        {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogIn2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LogIn2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool LogIn2Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Collections.Generic.Dictionary<int, int> solvedLevels;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public RoboZZle.WebService.LevelVoteInfo[] votes;
        
        public LogIn2Response()
        {
        }
        
        public LogIn2Response(bool LogIn2Result, System.Collections.Generic.Dictionary<int, int> solvedLevels, RoboZZle.WebService.LevelVoteInfo[] votes)
        {
            this.LogIn2Result = LogIn2Result;
            this.solvedLevels = solvedLevels;
            this.votes = votes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTopSolvers", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTopSolversRequest
    {
        
        public GetTopSolversRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTopSolversResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTopSolversResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] names;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int[] solved;
        
        public GetTopSolversResponse()
        {
        }
        
        public GetTopSolversResponse(string[] names, int[] solved)
        {
            this.names = names;
            this.solved = solved;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLevelVotes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLevelVotesRequest
    {
        
        public GetLevelVotesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLevelVotesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLevelVotesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int[] votes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int[] kinds;
        
        public GetLevelVotesResponse()
        {
        }
        
        public GetLevelVotesResponse(int[] votes, int[] kinds)
        {
            this.votes = votes;
            this.kinds = kinds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTopSolvers2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTopSolvers2Request
    {
        
        public GetTopSolvers2Request()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTopSolvers2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTopSolvers2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] names;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int[] solved;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] namesToday;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int[] solvedToday;
        
        public GetTopSolvers2Response()
        {
        }
        
        public GetTopSolvers2Response(string[] names, int[] solved, string[] namesToday, int[] solvedToday)
        {
            this.names = names;
            this.solved = solved;
            this.namesToday = namesToday;
            this.solvedToday = solvedToday;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLevelComments", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLevelCommentsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int levelId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pageNumber;
        
        public GetLevelCommentsRequest()
        {
        }
        
        public GetLevelCommentsRequest(int levelId, int pageNumber)
        {
            this.levelId = levelId;
            this.pageNumber = pageNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLevelCommentsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLevelCommentsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RoboZZle.WebService.CommentInfo[] GetLevelCommentsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool moreComments;
        
        public GetLevelCommentsResponse()
        {
        }
        
        public GetLevelCommentsResponse(RoboZZle.WebService.CommentInfo[] GetLevelCommentsResult, bool moreComments)
        {
            this.GetLevelCommentsResult = GetLevelCommentsResult;
            this.moreComments = moreComments;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface IRobozzleServiceChannel : RoboZZle.WebService.IRobozzleService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class RobozzleServiceClient : System.ServiceModel.ClientBase<RoboZZle.WebService.IRobozzleService>, RoboZZle.WebService.IRobozzleService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RobozzleServiceClient() : 
                base(RobozzleServiceClient.GetDefaultBinding(), RobozzleServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IRobozzleService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RobozzleServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(RobozzleServiceClient.GetBindingForEndpoint(endpointConfiguration), RobozzleServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RobozzleServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RobozzleServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RobozzleServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RobozzleServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RobozzleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<RoboZZle.WebService.GetLevelsResponse> GetLevelsAsync(RoboZZle.WebService.GetLevelsRequest request)
        {
            return base.Channel.GetLevelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<RoboZZle.WebService.GetLevels2Response> GetLevels2Async(RoboZZle.WebService.GetLevels2Request request)
        {
            return base.Channel.GetLevels2Async(request);
        }
        
        public System.Threading.Tasks.Task<RoboZZle.WebService.GetLevels3Response> GetLevels3Async(RoboZZle.WebService.GetLevels3Request request)
        {
            return base.Channel.GetLevels3Async(request);
        }
        
        public System.Threading.Tasks.Task<RoboZZle.WebService.GetLevelsPagedResponse> GetLevelsPagedAsync(RoboZZle.WebService.GetLevelsPagedRequest request)
        {
            return base.Channel.GetLevelsPagedAsync(request);
        }
        
        public System.Threading.Tasks.Task<RoboZZle.WebService.LevelInfo2> GetLevelAsync(int levelId)
        {
            return base.Channel.GetLevelAsync(levelId);
        }
        
        public System.Threading.Tasks.Task<RoboZZle.WebService.SubmitLevelResponse> SubmitLevelAsync(RoboZZle.WebService.SubmitLevelRequest request)
        {
            return base.Channel.SubmitLevelAsync(request);
        }
        
        public System.Threading.Tasks.Task<RoboZZle.WebService.SubmitLevel2Response> SubmitLevel2Async(RoboZZle.WebService.SubmitLevel2Request request)
        {
            return base.Channel.SubmitLevel2Async(request);
        }
        
        public System.Threading.Tasks.Task<RoboZZle.WebService.LogInResponse> LogInAsync(RoboZZle.WebService.LogInRequest request)
        {
            return base.Channel.LogInAsync(request);
        }
        
        public System.Threading.Tasks.Task<RoboZZle.WebService.LogIn2Response> LogIn2Async(RoboZZle.WebService.LogIn2Request request)
        {
            return base.Channel.LogIn2Async(request);
        }
        
        public System.Threading.Tasks.Task<string> SubmitSolutionAsync(int levelId, string userName, string password, string solution)
        {
            return base.Channel.SubmitSolutionAsync(levelId, userName, password, solution);
        }
        
        public System.Threading.Tasks.Task<string> RegisterUserAsync(string userName, string password, string email, int[] solvedLevels)
        {
            return base.Channel.RegisterUserAsync(userName, password, email, solvedLevels);
        }
        
        public System.Threading.Tasks.Task<string> RegisterUser2Async(string userName, string password, string email, System.Collections.Generic.Dictionary<int, string> solvedLevels)
        {
            return base.Channel.RegisterUser2Async(userName, password, email, solvedLevels);
        }
        
        public System.Threading.Tasks.Task<RoboZZle.WebService.GetTopSolversResponse> GetTopSolversAsync(RoboZZle.WebService.GetTopSolversRequest request)
        {
            return base.Channel.GetTopSolversAsync(request);
        }
        
        public System.Threading.Tasks.Task InternalAsync()
        {
            return base.Channel.InternalAsync();
        }
        
        public System.Threading.Tasks.Task SubmitLevelVoteAsync(string userName, string password, int levelId, int vote0, int vote1)
        {
            return base.Channel.SubmitLevelVoteAsync(userName, password, levelId, vote0, vote1);
        }
        
        public System.Threading.Tasks.Task<RoboZZle.WebService.GetLevelVotesResponse> GetLevelVotesAsync(RoboZZle.WebService.GetLevelVotesRequest request)
        {
            return base.Channel.GetLevelVotesAsync(request);
        }
        
        public System.Threading.Tasks.Task SubmitCommentAsync(string userName, string password, int puzzleId, string comment, string ipAddress)
        {
            return base.Channel.SubmitCommentAsync(userName, password, puzzleId, comment, ipAddress);
        }
        
        public System.Threading.Tasks.Task<RoboZZle.WebService.GetTopSolvers2Response> GetTopSolvers2Async(RoboZZle.WebService.GetTopSolvers2Request request)
        {
            return base.Channel.GetTopSolvers2Async(request);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, int>> GetLevelSolutionLengthsAsync(int levelId)
        {
            return base.Channel.GetLevelSolutionLengthsAsync(levelId);
        }
        
        public System.Threading.Tasks.Task<RoboZZle.WebService.GetLevelCommentsResponse> GetLevelCommentsAsync(RoboZZle.WebService.GetLevelCommentsRequest request)
        {
            return base.Channel.GetLevelCommentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<string[]> GetSolutionsAsync(string userName, string password, int puzzleId)
        {
            return base.Channel.GetSolutionsAsync(userName, password, puzzleId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRobozzleService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRobozzleService))
            {
                return new System.ServiceModel.EndpointAddress("http://www.robozzle.com/RobozzleService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RobozzleServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IRobozzleService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RobozzleServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IRobozzleService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IRobozzleService,
        }
    }
}
